### ISSUE TITLE
Deal with multiple RRSIGs over SOA

### ISSUE THREAD

**Issue by regnauld** [ableyjoe/checksig.sh#2]
If there are multiple RRSIGs over SOA, what is the behaviour ? If it happens, it is to be assumed that there is a valid key for each signature (leaving signatures in the zone which have no matching keys wouldn't make sense/be a bug from the signer ?)

Suggestion: pick the longest of the two remaining signature lifetimes.

**Comment by ableyjoe** [comment]
If there are multiple signatures, the tool only considers the signature with the lowest remaining validity. This seems like the conservative option (generate a spurious notification for something that is not important rather than ignoring a condition that might be a problem).
